Character.create(name: 'ルフィ（新世界）', image: 'luffy_new_world.png', category: 0, action_type: 0)
Character.create(name: 'ルフィ', image: 'luffy.png', category: 0, action_type: 0)
Character.create(name: 'ゾロ（新世界）', image: 'zoro_new_world.png', category: 0, action_type: 0)
Character.create(name: 'ゾロ', image: 'zoro.png', category: 0, action_type: 0)
Character.create(name: 'ナミ（新世界）', image: 'nami_new_world.png', category: 0, action_type: 2)
Character.create(name: 'ウソップ（新世界）', image: 'usopp_new_world.png', category: 0, action_type: 2)
Character.create(name: 'ウソップ', image: 'usopp.png', category: 0, action_type: 2)
Character.create(name: 'サンジ（新世界）', image: 'sanji_new_world.png', category: 0, action_type: 3)
Character.create(name: 'サンジ', image: 'sanji.png', category: 0, action_type: 1)
Character.create(name: 'チョッパー（新世界）', image: 'chopper_new_world.png', category: 0, action_type: 2)
Character.create(name: 'ロビン（新世界）', image: 'robin_new_world.png', category: 0, action_type: 2)
Character.create(name: 'フランキー（新世界）', image: 'franky_new_world.png', category: 0, action_type: 0)
Character.create(name: 'ブルック（新世界）', image: 'brook_new_world.png', category: 0, action_type: 1)
Character.create(name: '白ひげ', image: 'whitebeard.png', category: 1, action_type: 0)
Character.create(name: 'マルコ', image: 'marco.png', category: 1, action_type: 3)
Character.create(name: 'エース', image: 'ace.png', category: 1, action_type: 1)
Character.create(name: 'カイドウ', image: 'kaido.png', category: 1, action_type: 0)
Character.create(name: 'ビッグ・マム', image: 'big_mom.png', category: 1, action_type: 0)
Character.create(name: 'カタクリ', image: 'katakuri.png', category: 1, action_type: 1)
Character.create(name: 'シャンクス', image: 'shanks.png', category: 1, action_type: 0)
Character.create(name: 'ティーチ', image: 'teach.png', category: 1, action_type: 0)
Character.create(name: 'バルトロメオ', image: 'bartolomeo.png', category: 1, action_type: 2)
Character.create(name: 'キャベンディッシュ', image: 'cavendish.png', category: 1, action_type: 1)
Character.create(name: 'ロー', image: 'law.png', category: 2, action_type: 2)
Character.create(name: 'キッド', image: 'kid.png', category: 2, action_type: 0)
Character.create(name: 'ホーキンス', image: 'hawkins.png', category: 2, action_type: 2)
Character.create(name: 'ベッジ', image: 'bege.png', category: 2, action_type: 2)
Character.create(name: 'ミホーク', image: 'mihawk.png', category: 2, action_type: 0)
Character.create(name: 'ジンベエ', image: 'jinbe.png', category: 2, action_type: 0)
Character.create(name: 'ドフラミンゴ', image: 'doflamingo.png', category: 2, action_type: 3)
Character.create(name: 'クロコダイル', image: 'crocodile.png', category: 2, action_type: 3)
Character.create(name: 'ハンコック', image: 'hancock.png', category: 2, action_type: 2)
Character.create(name: 'バギー', image: 'buggy.png', category: 2, action_type: 2)
Character.create(name: '赤犬', image: 'akainu.png', category: 3, action_type: 0)
Character.create(name: '黄猿', image: 'kizaru.png', category: 3, action_type: 3)
Character.create(name: '藤虎', image: 'fujitora.png', category: 3, action_type: 0)
Character.create(name: 'スモーカー', image: 'smoker.png', category: 3, action_type: 3)
Character.create(name: 'たしぎ', image: 'tashigi.png', category: 3, action_type: 1)
Character.create(name: 'ルッチ', image: 'lucci.png', category: 4, action_type: 3)
Character.create(name: 'クザン', image: 'kuzan.png', category: 4, action_type: 2)
Character.create(name: 'サボ', image: 'sabo.png', category: 4, action_type: 1)
Character.create(name: 'イワンコフ', image: 'ivankov.png', category: 4, action_type: 2)
Character.create(name: 'キャロット', image: 'carrot.png', category: 4, action_type: 1)
Character.create(name: 'レイジュ', image: 'reiju.png', category: 4, action_type: 3)
Character.create(name: 'イチジ', image: 'ichiji.png', category: 4, action_type: 3)
Character.create(name: 'ニジ', image: 'niji.png', category: 4, action_type: 3)
Character.create(name: 'ヨンジ', image: 'yonji.png', category: 4, action_type: 3)
Character.create(name: 'スムージー', image: 'smoothie.png', category: 5, action_type: 0)
Character.create(name: 'クラッカー', image: 'cracker.png', category: 5, action_type: 1)
Character.create(name: 'ジャッジ', image: 'judge.png', category: 5, action_type: 3)
Character.create(name: 'ドレーク', image: 'drake.png', category: 5, action_type: 1)
Character.create(name: 'キラー', image: 'killer.png', category: 5, action_type: 1)
Character.create(name: 'ウルージ', image: 'urouge.png', category: 5, action_type: 0)
Character.create(name: 'お菊', image: 'okiku.png', category: 5, action_type: 1)
Character.create(name: '錦えもん', image: 'kinemon.png', category: 5, action_type: 0)
Character.create(name: 'おでん', image: 'oden.png', category: 5, action_type: 0)

Stage.create(name: 'アルバーナ', image: 'alubarna.jpg')
Stage.create(name: 'エニエス・ロビー', image: 'enies_lobby.jpg')
Stage.create(name: 'マリンフォード', image: 'marineford.jpg')
Stage.create(name: '海軍本部', image: 'marine_headquarters.jpg')
Stage.create(name: 'ドレスローザ', image: 'dressrosa.jpg')
Stage.create(name: 'ホールケーキアイランド', image: 'whole_cake_island.jpg')
Stage.create(name: '鏡世界', image: 'mirror_world.jpg')
Stage.create(name: '鬼ヶ島', image: 'onigashima.jpg')

User.create(name: 'Sylpha', email: 'sylpha.games@gmail.com', password: 'sayumi729864')
